server:
  port: 3200
  servlet:
     context-path: /api/v1/jlmorab/ms-sales

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASW}
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    hikari:
      minimumIdle: 1
      maximumPoolSize: 4
      idleTimeout: 15000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 1800000
      connectionTimeout: 120000

  sql:
    init:
      encoding: UTF-8
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: none